version: '3.8'

services:
    # Web Server
    web:
        image: wordpress:php7.4-fpm-alpine
        container_name: "${APP_NAME}_web"
        working_dir: /var/www/html
        volumes:
            - ./target:/var/www/html
        environment:
            - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
            - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
            - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
            - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}:3306
        ports:
            - ${APP_PORT}:80
        networks:
            - ${APP_NETWORK}
        # Wait for "database" container to start first
        depends_on:
            - database

    # Database
    database:
        image: mysql:8.0
        container_name: "${APP_NAME}_database"
        volumes:
            - ./data:/var/lib/mysql 
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        ports:
            - ${DB_PORT}:${DB_PORT}
        networks:
            - ${APP_NETWORK}

    # Database management
    pma:
        image: phpmyadmin:latest
        container_name: "${APP_NAME}_pma" 
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=${DB_PMA_HOST}
            - PMA_USER=${DB_USERNAME}
            - PMA_PASSWORD=${DB_PASSWORD}
            - PMA_PORT=${DB_PORT}
        ports:
            - ${DB_PMA_PORT}:80
        networks:
            - ${APP_NETWORK}
        # Wait for "database" container to start first
        depends_on:
            - database

# Define networks
networks:
    portfolio:
        driver: bridge
